### ISSUE TITLE
Issue compiling build script

### ISSUE THREAD

**Issue by nstoddard** [bjz/gl-rs#268]
With the latest Rust and Cargo (Windows 7 64-bit), I get a strange error when trying to compile my app which uses a build script to enable some OpenGL extensions:

```
build.rs:1:1: 1:27 error: can't find crate for `gl_generator`
build.rs:1 extern crate gl_generator;
```

If I repeatedly run `cargo run`, it eventually works. It appears that it's trying to compile my build script before its dependency on gl_generator. What's going on here? I'm not sure if it's a bug in gl-rs or in Cargo.

**Comment by tomaka** [comment]
Are you using `[build-dependency]`? (`[dependency]` is wrong)

**Comment by nstoddard** [comment]
That fixed it, thanks! Can you update the readme to make this clear?
