### ISSUE TITLE
Kronos crate not being pulled in

### ISSUE THREAD

**Issue by nathansizemore** [bjz/gl-rs#279]
`cant find crate for kronos_api` when building with latest rustc and cargo.

I'm assuming cargo used to pull in sub-modules and init them, but doesn't now, or setting for that changed?

**Comment by csherratt** [comment]
I think https://github.com/bjz/gl-rs/pull/278 fixed this?

**Comment by nathansizemore** [comment]
If I clone the project, and then init and update submodule, it works as expected, but including this a dependency in a project with gl_generator, and compiling with cargo, it fails.
gfx_gl is failing as well when using it with the build.rs.
When building with the 1.0a release of rustc and cargo, it was working, but just updated today and it is failing with: 

`rustc 1.0.0-nightly (ed530d7a3 2015-01-16 22:41:16 +0000)`

`cargo 0.0.1-pre-nightly (8154255 2015-01-14 19:14:12 +0000)`

**Comment by tomaka** [comment]
The problem doesn't come from gl-rs, but from the crates that uses it. You need to add a build-dependency to `khronos_api`, like this: https://github.com/tomaka/glium/pull/307/files

**Comment by nathansizemore** [comment]
That does work.  Thanks.
