### ISSUE TITLE
Error when publishing to crates.io

### ISSUE THREAD

**Issue by bvssvni** [bjz/gl-rs#283]
I'm trying to update piston2d-opengl_graphics on crates.io, but getting an error:

```
:1: 2:26 error: can't find crate for `khronos_api`
../../.cargo/registry/src/github.com-1ecc6299db9ec823/gl-0.0.5/src/gl/build.rs:2 extern crate khronos_api;
                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tomaka** [comment]
You need to add `[build-dependencies] khronos_api = "*"` in piston2d-opengl_graphic's Cargo.toml

**Comment by bvssvni** [comment]
Still getting same error.

The version should probably be bumped to "0.0.6"?

**Comment by tomaka** [comment]
This was fixed on IRC if I remember correctly
