### ISSUE TITLE
"cargo doc" generates huge amounts of documentation when using gl_generator

### ISSUE THREAD

**Issue by nstoddard** [bjz/gl-rs#288]
When using gl_generator with a custom build script, `cargo doc` generates hundreds of megabytes of documentation for the generated bindings. This documentation isn't very useful and takes forever to generate; is there a way to stop cargo from generating it?

**Comment by tomaka** [comment]
The docs for the bindings are generated only if the bindings are public.

For example glutin [uses OpenGL bindings](https://github.com/tomaka/glutin/blob/master/build.rs), but there is no mention about the bindings in [the generated docs](http://tomaka.github.io/glutin/glutin/index.html).

**Comment by cmr** [comment]
You can also put `#[doc(hidden)]` on it.
