### ISSUE TITLE
Closure syntax update + Reminder

### ISSUE THREAD

**Issue by toqueteos** [bjz/gl-rs#302]
I was about to send a PR about this but compiler is complaining about two different `*const libc::types::common::c95::c_void` enum types which I don't know how to solve so...

# Reminder

Don't forget to change [this line](https://github.com/bjz/gl-rs/blob/8dced16925dd6c08cbf65bac380a8b802db9fc3d/src/gl_generator/generators/struct_gen.rs#L187) from:

```rust
let mut metaloadfn = |&mut: symbol: &str, symbols: &[&str]| {{
```
to:
```rust
let mut metaloadfn = |symbol: &str, symbols: &[&str]| {{
```

**Comment by kvark** [comment]
This should have been fixed by #299
Try syncing up?

**Comment by bjz** [comment]
Re-running travis

**Comment by toqueteos** [comment]
Already fixed, closing.
