### ISSUE TITLE
Use of log (debug!, warn!) seems to cause issues.

### ISSUE THREAD

**Issue by Limvot** [bjz/gl-rs#317]
On the current nightly, weird errors result from gl-rs's use of the log crate. Possibly this is an issue with log.
Errors look like:

   Compiling gl_generator v0.0.18 (https://github.com/bjz/gl-rs#9d941381)
<log macros>:4:8: 4:21 error: mismatched types:
 expected `usize`,
    found `u32`
(expected usize,
    found u32) [E0308]
<log macros>:4 line : line ! (  ) , file : file ! (  ) , module_path : module_path ! (  ) , }

**Comment by cantsin** [comment]
The log dependency needs to be updated, but cargo doesn't have a newer log version (currently at `0.2.4`). Will need to wait until a new version is published; in the meantime, commenting out all `debug!` and `warn!` lines in `src/gl_generator/registry.rs` will allow gl-rs to compile.

**Comment by tomaka** [comment]
Fixed now
