### ISSUE TITLE
Repository reorganization

### ISSUE THREAD

**Issue by tomaka** [bjz/gl-rs#320]
Proposition:

- Move everything related to the `gl` crate (`Cargo.toml`, `src/gl`, `tests` and `examples`) in a `gl` subdirectory.
- Move `gl_generator`, `khronos_api` and `gl_common` directories from `src` to the crate root.
- Add a `gl_tests` crate (which we won't publish) that is used to test the output of `gl_generator` instead of `gl` itself (solves #314).

All five crates (`gl`, `gl_generator`, `gl_common`, `khronos_api`, `gl_tests`) would be at the same level at the root of the repository, alongside with `.gitignore`, `.travis.yml`, etc.

**Comment by bjz** [comment]
:+1:
