### ISSUE TITLE
`gl::load_with()` unsafety?

### ISSUE THREAD

**Issue by nukep** [bjz/gl-rs#337]
Continuing from the discussion from https://github.com/AngryLawyer/rust-sdl2/pull/402#issuecomment-101636416

As of writing, `gl::load_with()` requires a closure that returns a raw pointer to a GL function.
It seems to return `*const libc::c_void` (which btw contradicts with what the README says: `Option<extern "C" fn()>`).

I believe that as it currently stands, `gl::load_with()` is inherently unsafe because it's responsible for pointer dereferencing through virtual dispatch. Should `gl::load_with()` be marked `unsafe`?
```rust
// no `unsafe` is required. D:
gl::load_with(|_name| 0xDEADBEEF as *const _);
```

**Comment by AngryLawyer** [comment]
Definitely.

**Comment by cmr** [comment]
@nukep no, it is not inherently unsafe. What is inherently unsafe is *later calling* the `gl` functions. All of which are unsafe. `load_with` never dereferences a pointer.

**Comment by nukep** [comment]
Fair enough. All of the `gl` functions are marked `unsafe`, so that would take care of it, huh?

**Comment by cmr** [comment]
Yes.
