### ISSUE TITLE
Triangle becomes a square when I change 'static' to 'const'

### ISSUE THREAD

**Issue by bohdan-shulha** [bjz/gl-rs#344]
Hi there!

Recently I went into issue when I did a research of this amazing platform (Rust).

I've used slightly [modified code](https://gist.github.com/bohdan-shulha/dbcf83d6ba8044e7ed20) from [static_triangle.rs](https://github.com/bjz/gl-rs/blob/master/gl/examples/static_triangle.rs) to match the most recent (1.0) version of Rust and get it running.

But when I tried to switch [allocation model](http://static.rust-lang.org/doc/stable/book/const-and-static.html) from static to const ([line 33](https://gist.github.com/bohdan-shulha/dbcf83d6ba8044e7ed20#file-gistfile1-rs-L33)) everything went wrong: my triangle at the center of the screen became the square at the top right corner.

Using [static (.png)](https://cloud.githubusercontent.com/assets/533048/7945676/f2d59ce4-097a-11e5-8306-c04b8a8a18c6.png)
Using [const (.png)](https://cloud.githubusercontent.com/assets/533048/7945677/f2d66a0c-097a-11e5-92ab-6124844b4d56.png)

Did anyone faced with it? Is it just my misunderstanding or a library bug? Or even a compiler bug?

Thanks.

P.S.: I am sorry for misspellings if any, I am not a good friend with English :(

**Comment by cmr** [comment]
@bohdan-shulha This is a classic case of "dangling pointer". When you use a `const`, there is no fixed location that the data of is stored at, as opposed to a `static` which does have a fixed location in the read-only section of the executable. So when you write `mem::transmute(&VERTEX_DATA[0])`, the pointer will be to a "random" place on the stack.

Don't use `const` for this!

**Comment by cmr** [comment]
(I recommend using glium or gfx-rs or another of the higher-level wrappers around gl-rs instead of raw gl-rs.)

**Comment by bohdan-shulha** [comment]
Ohh. 
I've learned that Rust was designed to prevent dangling pointers so I was not even close in my minds to the source of this issue (which is caused by unsafe{}, am I right?).

I've seen gfx-rs a bit earlier but I didn't gave much attention to it, now I will look closer.

Thank you for a super-fast response and sorry for inconvenience. I must go deeper into the language before asking such questions :(

Good luck!

**Comment by cmr** [comment]
No worries, happy to help. The issue isn't only the unsafe (you can easily make a dangling raw pointer in safe code, just with casts), but what the functions are doing with the raw pointer.
