### ISSUE TITLE
Outdated info about custom generators in README

### ISSUE THREAD

**Issue by mjkoo** [bjz/gl-rs#361]
Hello,

It looks like the "Custom Generators" section of the readme references an older method of generating custom bindings, based on the information in https://github.com/bjz/gl-rs/pull/239

To me it seems like the current correct way to use this functionality is to create a struct implementing `gl_generator::generators::Generator` and pass this to `gl_generator::generate_bindings` from your `build.rs`, is this case?

**Comment by bjz** [comment]
Thanks for noting - this is important. I'm slowly updating the docs as I do my push towards a 1.0 release.

**Comment by bjz** [comment]
I believe this is fixed!
