### ISSUE TITLE
Mismatched type `c_void` when trying to use gl-generator

### ISSUE THREAD

**Issue by codingcampbell** [bjz/gl-rs#362]
This is with rust 1.4 on OSX 10.11. I'm trying the steps for using gl-generator, which has worked for me in the past (a few weeks ago), but now I get this message with just building main.rs and build.rs from the README:
>
/target/debug/build/gl-test-b19ef746b2659244/out/bindings.rs:23225:30: 23225:56 error: mismatched types:
 expected `*const gles::__gl_imports::libc::c_void`,
    found `*const libc::types::common::c95::c_void`
(expected enum `gles::__gl_imports::libc::c_void`,
    found enum `libc::types::common::c95::c_void`) [E0308]
/target/debug/build/gl-test-b19ef746b2659244/out/bindings.rs:23225             load_with(|name| loader.get_proc_addr(name));
                                                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.rs:2:5: 2:56 note: in this expansion of include!
/target/debug/build/gl-test-b19ef746b2659244/out/bindings.rs:23225:30: 23225:56 help: run `rustc --explain E0308` to see a detailed explanation

Is the README outdated? Cargo.lock shows these versions:

>
dependencies = [
 "gl 0.2.0 (git+https://github.com/bjz/gl-rs)",
 "gl_common 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "gl_generator 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "khronos_api 0.0.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)",
]

**Comment by bjz** [comment]
Could you try bumping to `gl = "0.3"`, then running `cargo update`?

**Comment by codingcampbell** [comment]
Thanks @bjz that seems to work. For reference, these were the resulting versions after update:

>
 "gl 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "gl_common 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "gl_generator 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "khronos_api 0.0.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)",
