### ISSUE TITLE
Use gl::EnableClientState and gl::VertexPointer doesnt work

### ISSUE THREAD

**Issue by b-pos465** [bjz/gl-rs#365]
Im trying to use this:
```
gl::EnableClientState();
```

The compiler throws: 

> unresolved name `gl::EnableClientState` [E0425]

I was looking for this function in the bindings.rs and didn't find it. Will it be supported in the future?

**Comment by tomaka** [comment]
That's a function from OpenGL 1 that has been deprecated and removed in OpenGL 3. It's not in the bindings on purpose.

**Comment by b-pos465** [comment]
Ok, i kind of suggested this. I've found this function in a lot of examples (like this one: http://stackoverflow.com/questions/6940708/what-is-the-purpose-of-enable-client-state) looking for a good way to load vertex _and_ normal data into my vertex shader. 

I already created a VBO containing both. The thing Im looking for right now is how to tell OpenGL to make my normal values get accesable by my vertex shader. Could you give me a hint: What is the up-to-date way of doing this?

**Comment by bjz** [comment]
A quick google for `glEnableClientState` gives: http://stackoverflow.com/a/11807263

**Comment by bjz** [comment]
Closing because we don't support the deprecated OpenGL APIs. Fell free to ask more questions though! :)
