### ISSUE TITLE
0.4.0 release

### ISSUE THREAD

**Issue by bvssvni** [bjz/gl-rs#366]
- https://github.com/bjz/gl-rs/pull/364 replaced `libc::c_void` with `()`, but this has not been published yet
- There are some broken examples https://github.com/bjz/gl-rs/pull/339
- @tomaka suggested a stable API for gl_generator in https://github.com/bjz/gl-rs/issues/338

**Comment by bvssvni** [comment]
We might want to implement the changes in gl_generator first, to avoid breaking Glium later.

The "struct_triangle" example could be removed, unless there is a way to use a build script in the examples.

**Comment by bjz** [comment]
Sorry for the delay - I'll get on with this tonight.

**Comment by tomaka** [comment]
Let's maybe change `*const ()` with `*const std::os::raw::c_void` again? (#364 in another way)

**Comment by bjz** [comment]
Yes, I would prefer that.
