### ISSUE TITLE
*const GLvoid is incompatible with *const raw::c_void

### ISSUE THREAD

**Issue by vickenty** [bjz/gl-rs#375]
For example, lets take ``glVertexAttribPointer()``, a function that in certain cases expects integer offsets in a pointer argument (actual pointer is supplied via another call). If a programmer writes code according to the [OpenGL documentation](https://www.opengl.org/sdk/docs/man/html/glVertexAttribPointer.xhtml), she might write code like this  ([full text](https://gist.github.com/vickenty/135f9ab9ed835ddef4bc)):
```rust
let offset = 4;
gl::VertexAttribPointer(
    0, 2, gl::FLOAT, false, 0,
    offset as *const gl::types::GLvoid
);
```
But since gl::VertexAttribPointer actually expects ``*const raw::c_void``, it doesn't compile:
```
main.rs:8:13: 8:47 error: mismatched types:
 expected `*const std::os::raw::c_void`,
    found `*const ()`
(expected enum `std::os::raw::c_void`,
    found ()) [E0308]
main.rs:8             offset as *const gl::types::GLvoid
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This is due to the fact that ``GLvoid`` is defined as an alias to ``()``, and gl::VertexAttribPointer expects ``*const raw::c_void``. When gl-rs was using ``libc::c_void`` as a base for all GLvoid and void types and pointers, these pointer types were compatible and the code used to compile without error.

A real life example of this can be found in the [sources of gfx-rs/gfx](https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/factory.rs#L122).

**Comment by bjz** [comment]
cc. @tomaka #373
