### ISSUE TITLE
Autogenerated glx/egl bindings now require explicit loading?

### ISSUE THREAD

**Issue by emilio** [bjz/gl-rs#403]
Hi, when trying to update `gl_generator` to version `0.5` [here](https://github.com/emilio/rust-offscreen-rendering-context/pull/52), I'm seeing that calling a `glx` function will fail with something like:

```
thread 'tests::test_sharing' panicked at 'glx function was not loaded'
```

Is this intended? If it is, how can you load them (`glx::GetProcAddress`? I don't think so), or restore the previous behaviour?

**Comment by emilio** [comment]
Previously generated code:

```rust
#[link_name="glXChooseFBConfig"]
            pub fn ChooseFBConfig(dpy: *mut types::Display, screen: __gl_imports::raw::c_int, attrib_list: *const __gl_imports::raw::c_int, nelements: *mut __gl_imports::raw::c_int) -> *mut types::GLXFBConfig;
```

Generated with 0.5:

```rust
#[allow(non_snake_case, unused_variables, dead_code)] #[inline]
            pub unsafe fn ChooseFBConfig(dpy: *mut types::Display, screen: __gl_imports::raw::c_int, attrib_list: *const __gl_imports::raw::c_int, nelements: *mut __gl_imports::raw::c_int) -> *mut types::GLXFBConfig { __gl_imports::mem::transmute::<_, extern "system" fn(*mut types::Display, __gl_imports::raw::c_int, *const __gl_imports::raw::c_int, *mut __gl_imports::raw::c_int) -> *mut types::GLXFBConfig>(storage::ChooseFBConfig.f)(dpy, screen, attrib_list, nelements) }
```

**Comment by tomaka** [comment]
The PR you linked changes `StaticGenerator` into `GlobalGenerator`.
The static generator links to the function at compile-time, while the global generator must be loaded at runtime.

**Comment by emilio** [comment]
Whoops, sleepy me in the mornings... Thanks! (and sorry)
