### ISSUE TITLE
OpenGL extensions

### ISSUE THREAD

**Issue by Baransu** [bjz/gl-rs#404]
I'm wondering is it possible to check extensions capabilities? Especially I want to implement anisotropic filtering and don't know how to check if it is supported. I'm using glium for windows handling.

**Comment by cmr** [comment]
You're using glutin for window handling, glium is a GL wrapper. You need to use glGetString. For an example, see https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/info.rs

For questions like this, ask in #rust-gamedev on IRC or google for generic GL information, there's nothing special specific to this library.

**Comment by bjz** [comment]
I think it is a reasonable question to ask @cmr. At least now we have a record to point people towards in the future. Thanks for answering though!

**Comment by cmr** [comment]
It's a reasonable question to ask for sure! Issues, though, are not ideal IMO.

**Comment by bjz** [comment]
Yeah - I guess it is an annoying limitation of Github. It's hard to communicate asynchronously outside of issues.

**Comment by Baransu** [comment]
Thank you for the help :)
